version: "3.8"
services:
  redis:
    image: redis:alpine
    volumes:
      - ./redis-data:/data
    ports:
      - "6379"
    networks:
      - bot
    restart: "always"
  worker:
    image: francescorw/idiomatic:1.0
    depends_on: [redis]
    networks:
      - bot
    environment:
      - TELEGRAM_TOKEN
      - IDM_ADMINS
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: "always"

networks:
  bot: